version: '3'

services:
  redis:
    build: ./redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
