name: QA

on:
  push:
    branches: ["main", "preview"]
  pull_request:
    branches: ["main", "preview"]

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        id: deno_setup
        with:
          deno-version: v1.x

      - name: Format
        if: success() || (failure() && steps.deno_setup.conclusion == 'success')
        run: deno fmt --check

      - name: Lint
        if: success() || (failure() && steps.deno_setup.conclusion == 'success')
        run: deno lint
      
      - name: Type check
        if: success() || (failure() && steps.deno_setup.conclusion == 'success')
        run: deno check ./src/run-wh.ts && deno check ./src/run-lp.ts

      - name: Test
        if: success() || (failure() && steps.deno_setup.conclusion == 'success')
        run: deno test -A
